import os
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from dotenv import load_dotenv

# Load dependencies
load_dotenv()

from aws_rag_app.src.services.bedrock_service import BedrockService
from aws_rag_app.src.services.opensearch_service import OpenSearchService

app = FastAPI(
    title="AWS Bedrock & OpenSearch RAG App",
    description="Privacy-compliant vector retrieval system for furniture inventories.",
    version="1.0.0"
)

# Initialize service classes
try:
    bedrock = BedrockService()
    opensearch = OpenSearchService()
except Exception as e:
    print(f"Warning: Client initialization failed (AWS configs might be missing): {e}")

# Request Models
class QueryRequest(BaseModel):
    query: str
    top_k: int = 3

class QueryResponse(BaseModel):
    answer: str
    sources: list

@app.get("/health")
def health_check():
    return {"status": "healthy", "service": "aws-rag-app"}

@app.post("/query", response_model=QueryResponse)
def query_rag(request: QueryRequest):
    """
    Query the RAG pipeline. Generates embeddings, retrieves documents from OpenSearch,
    and returns an answer generated by Claude 3.5.
    """
    if not request.query.strip():
        raise HTTPException(status_code=400, detail="Query cannot be empty.")
        
    try:
        # 1. Embed user query using Titan Embeddings
        query_vector = bedrock.get_embeddings(request.query)
        
        # 2. Retrieve top matching spec sheets from OpenSearch Serverless
        search_results = opensearch.search_similar_documents(query_vector, top_k=request.top_k)
        
        if not search_results:
            return QueryResponse(
                answer="I couldn't find any relevant inventory records in the vector database to answer your question.",
                sources=[]
            )
            
        # 3. Concatenate text outputs for context window
        context_chunks = []
        sources = []
        for i, doc in enumerate(search_results):
            context_chunks.append(f"[Source {i+1}]: {doc.get('text')}")
            sources.append({
                "id": doc.get("id"),
                "score": doc.get("score"),
                "metadata": doc.get("metadata")
            })
            
        context_str = "\n\n".join(context_chunks)
        
        # 4. Invoke Bedrock LLM (Claude 3.5 Sonnet) with context
        answer = bedrock.generate_grounded_answer(request.query, context_str)
        
        return QueryResponse(answer=answer, sources=sources)
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"RAG search error: {str(e)}")

@app.post("/sync")
def trigger_sync():
    """
    Simulates triggering the ingestion worker to load records from the production DB,
    redact PII locally, and store embeddings in OpenSearch Serverless.
    """
    # Under Fargate, this endpoint might trigger a task execution via AWS ECS API.
    # Locally, we run a mock ingestion for validation.
    return {"message": "Sync pipeline triggered. Check ingestion tasks on ECS Fargate."}

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    host = os.getenv("HOST", "0.0.0.0")
    uvicorn.run(app, host=host, port=port)
