import os
import boto3
import json
from typing import List

class BedrockService:
    def __init__(self):
        # AWS default settings
        self.region = os.getenv("AWS_DEFAULT_REGION", "us-east-1")
        self.llm_model_id = os.getenv("BEDROCK_LLM_MODEL_ID", "anthropic.claude-3-5-sonnet-20240620-v1:0")
        self.embedding_model_id = os.getenv("BEDROCK_EMBEDDING_MODEL_ID", "amazon.titan-embed-text-v2:0")
        
        # Initialize Bedrock Runtime client
        self.client = boto3.client(
            service_name="bedrock-runtime",
            region_name=self.region
        )

    def get_embeddings(self, text: str) -> List[float]:
        """
        Generates vector embeddings for a given text input using the Amazon Titan Embedding model.
        """
        if not text or not text.strip():
            return []
            
        try:
            # Titan Embed Text v2 payload structure
            payload = {
                "inputText": text,
                "dimensions": 1024,
                "normalize": True
            }
            
            body = json.dumps(payload)
            response = self.client.invoke_model(
                body=body,
                modelId=self.embedding_model_id,
                accept="application/json",
                contentType="application/json"
            )
            
            response_body = json.loads(response.get("body").read())
            embeddings = response_body.get("embedding")
            return embeddings
            
        except Exception as e:
            print(f"Error generating embeddings with model {self.embedding_model_id}: {e}")
            raise e

    def generate_grounded_answer(self, query: str, context: str) -> str:
        """
        Queries Claude 3.5 Sonnet to generate an answer grounded in the retrieved OpenSearch context.
        """
        # Formulate grounded prompt
        system_instruction = (
            "You are a helpful product support assistant. Answer the user's query using only the "
            "provided search context. If the context does not contain the answer, politely state "
            "that you do not have enough information to answer."
        )
        
        prompt_content = f"Search Context:\n{context}\n\nUser Query: {query}\n\nAnswer:"
        
        try:
            # Claude 3.5 Bedrock runtime payload structure
            payload = {
                "anthropic_version": "bedrock-2023-05-31",
                "max_tokens": 500,
                "system": system_instruction,
                "messages": [
                    {
                        "role": "user",
                        "content": [
                            {
                                "type": "text",
                                "text": prompt_content
                            }
                        ]
                    }
                ],
                "temperature": 0.2
            }
            
            body = json.dumps(payload)
            response = self.client.invoke_model(
                body=body,
                modelId=self.llm_model_id,
                accept="application/json",
                contentType="application/json"
            )
            
            response_body = json.loads(response.get("body").read())
            contents = response_body.get("content", [])
            if contents:
                return contents[0].get("text")
            return "No response content generated by LLM."
            
        except Exception as e:
            print(f"Error generating LLM response with model {self.llm_model_id}: {e}")
            raise e
