import { stitch } from '@google/stitch-sdk';

// Check for the Google Stitch API Key in the environment variables
const STITCH_API_KEY = import.meta.env.VITE_STITCH_API_KEY || '';

class StitchIntegration {
  private isInitialized = false;

  constructor() {
    if (STITCH_API_KEY) {
      // Typically, setting the API key or configuring the client is done here.
      // Depending on the `@google/stitch-sdk` exact API:
      // stitch.setApiKey(STITCH_API_KEY);
      this.isInitialized = true;
      console.log('[Stitch SDK] Google Stitch client initialized successfully.');
    } else {
      console.warn(
        '[Stitch SDK] VITE_STITCH_API_KEY environment variable is not defined. Running in mock fallback mode.'
      );
    }
  }

  /**
   * Generates a UI component representation from a prompt description
   */
  async generateComponent(prompt: string): Promise<{ html: string; image?: string; success: boolean }> {
    if (!this.isInitialized) {
      // Mock/Fallback response when API key is missing
      console.log(`[Stitch SDK (Mock)] Generating layout for: "${prompt}"`);
      await new Promise((resolve) => setTimeout(resolve, 1500)); // Simulate API latency
      
      const mockHtml = `
        <div class="p-6 rounded-lg bg-neutral-900 border border-orange-500/20 text-center">
          <h4 class="text-orange-500 font-bold mb-2">Generated component for: "${prompt}"</h4>
          <p class="text-sm text-neutral-400">This is a mock UI component generated by the Google Stitch client shell. Set VITE_STITCH_API_KEY in your environment to load live generative UI designs.</p>
        </div>
      `;
      return { html: mockHtml, success: true };
    }

    try {
      // Call official Google Stitch SDK methods
      const project = await stitch.createProject("BlindLabs.Dev Workspace");
      const screen = await project.generate(prompt);
      
      const html = await screen.getHtml();
      const image = await screen.getImage();

      return { html, image, success: true };
    } catch (error) {
      console.error('[Stitch SDK] Component generation failed:', error);
      return { 
        html: `<div class="text-red-500">Failed to render component: ${(error as Error).message}</div>`, 
        success: false 
      };
    }
  }
}

export const stitchClient = new StitchIntegration();
export default stitchClient;
